language: cpp
dist: bionic
arch: ppc64le
os: linux
addons:
  apt:
    packages:
      - "libsodium-dev"
      - "libsdl2-mixer-dev"
      - "libsdl2-ttf-dev"
jobs:
  include:
  - stage: Linux
    install:
      - sudo apt-get -qq update
      - mkdir -p build
      - cd build
      - cmake .. -DBINARY_RELEASE=ON
    script:
      - cmake --build . --target package -- -j $(nproc)
