language: cpp
dist: bionic
compiler:
- g++
os:
- linux
before_install: sudo apt-get -qq update && sudo apt-get -qq install libsodium-dev libsdl2-mixer-dev libsdl2-ttf-dev
install: sudo apt-get -qq update && mkdir -p build && cd build && cmake .. -DBINARY_RELEASE=ON
script: cmake --build . --target package -- -j $(nproc)
